<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$u=require_user();
function group_by_code(string $code): ?array {foreach(read_collection('group_chats') as $g)if(($g['code']??'')===$code)return $g;return null;}
function group_public(array $g): array {$members=[];foreach($g['memberUserIds']??[] as $id){$m=user_by_id((string)$id);if($m)$members[]=public_user($m);}return ['id'=>$g['id'],'code'=>$g['code'],'url'=>'https://xtratype.com/gc/'.$g['code'],'name'=>$g['name']??'XT Group Chat','createdByUserId'=>$g['createdByUserId'],'members'=>$members,'createdAt'=>$g['createdAt'],'updatedAt'=>$g['updatedAt']??$g['createdAt']];}
function require_group_member(array $g,array $u): void {if(!in_array($u['id'],$g['memberUserIds']??[],true))fail('You do not have access to this XT Group Chat.',403,'groupAccessDenied');}
function update_profile_group_chat(string $userId,array $chat): void {$items=profile_read($userId,'group-chats',[]);$public=['code'=>$chat['code'],'url'=>'https://xtratype.com/gc/'.$chat['code'],'name'=>$chat['name']??'XT Group Chat','addedAt'=>gmdate('c')];$found=false;foreach($items as $i=>$row)if(($row['code']??'')===$chat['code']){$items[$i]=[...$row,...$public];$found=true;}if(!$found)$items[]=$public;profile_write($userId,'group-chats',$items);}
if($_SERVER['REQUEST_METHOD']==='GET'){$code=isset($_GET['code'])?(string)$_GET['code']:'';if($code!==''){if(!preg_match('/^[A-Za-z0-9]{5}$/',$code))fail('Invalid group chat code.');$g=group_by_code($code);if(!$g)fail('Group chat not found.',404,'groupNotFound');require_group_member($g,$u);$msgs=array_values(array_filter(read_collection('group_messages'),fn($m)=>($m['chatCode']??'')===$code));usort($msgs,fn($a,$b)=>strcmp($a['createdAt']??'',$b['createdAt']??''));respond(['ok'=>true,'chat'=>group_public($g),'messages'=>array_map('decorate_group_message',array_slice($msgs,-300))]);}$items=[];foreach(read_collection('group_chats') as $g)if(in_array($u['id'],$g['memberUserIds']??[],true))$items[]=group_public($g);respond(['ok'=>true,'items'=>$items]);}
if($_SERVER['REQUEST_METHOD']!=='POST')fail('Method not allowed.',405);$p=json_body();$action=bounded_string($p['action']??null,'action',40);
if($action==='create'){$name=trim((string)($p['name']??'XT Group Chat'));if($name==='')$name='XT Group Chat';if(strlen($name)>100)fail('Group chat name is too long.');$names=$p['memberUsernames']??[];if(!is_array($names)||count($names)>100)fail('A group chat supports up to 100 invited users at creation.');$ids=[$u['id']];foreach($names as $n){$m=user_by_username(validate_username($n));if(!$m||($m['enabled']??true)!==true)fail('Unknown or disabled user: '.$n);if(!in_array($m['id'],$ids,true))$ids[]=$m['id'];}$existing=array_flip(array_map(fn($g)=>(string)($g['code']??''),read_collection('group_chats')));do{$code=random_base62(5);}while(isset($existing[$code]));$now=gmdate('c');$g=['id'=>'groupchat:'.$code,'code'=>$code,'name'=>$name,'createdByUserId'=>$u['id'],'memberUserIds'=>$ids,'createdAt'=>$now,'updatedAt'=>$now];upsert_item('group_chats',$g);foreach($ids as $id)update_profile_group_chat($id,$g);respond(['ok'=>true,'chat'=>group_public($g)],201);}
if($action==='grant'){$code=bounded_string($p['code']??null,'code',5);$g=group_by_code($code);if(!$g)fail('Group chat not found.',404,'groupNotFound');if(($g['createdByUserId']??'')!==$u['id'])fail('Only the group chat creator can grant access.',403,'groupGrantDenied');$m=user_by_username(validate_username($p['username']??null));if(!$m||($m['enabled']??true)!==true)fail('User not found or disabled.',404,'userNotFound');if(!in_array($m['id'],$g['memberUserIds'],true))$g['memberUserIds'][]=$m['id'];$g['updatedAt']=gmdate('c');upsert_item('group_chats',$g);update_profile_group_chat($m['id'],$g);respond(['ok'=>true,'chat'=>group_public($g)]);}
if($action==='message'){$code=bounded_string($p['code']??null,'code',5);$g=group_by_code($code);if(!$g)fail('Group chat not found.',404,'groupNotFound');require_group_member($g,$u);$body=trim(bounded_string($p['body']??null,'Message',20000));$item=['id'=>uuid_like('groupmessage'),'chatCode'=>$code,'senderUserId'=>$u['id'],'body'=>$body,'createdAt'=>gmdate('c')];upsert_item('group_messages',$item);respond(['ok'=>true,'item'=>decorate_group_message($item)],201);}
fail('Unknown group chat action.');
