<?php require __DIR__.'/api/bootstrap.php'; header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#172033"><title>XtraType</title><link rel="stylesheet" href="assets/style.css"></head>
<body data-default-radius="<?= (int)$config['default_gps_radius_meters'] ?>">
<header><div class="brand"><span>XT</span><div><strong>XtraType</strong><small>Context, saved with care</small></div></div><button id="locate">Use location</button></header>
<nav><button data-tab="post" class="active">Post</button><button data-tab="nearby">Nearby</button><button data-tab="feed">All context</button><button data-tab="schemas">Schemas</button><button data-tab="account">Account</button></nav>
<main>
<section id="tab-post" class="tab active">
<form id="post-form" class="card">
<div class="title"><b>Attach context</b><span class="pill">server + mobile</span></div>
<label>Attach to<select id="target-kind"></select></label><div id="target-fields"></div>
<label>Highlighted / quoted text<textarea id="highlighted" rows="2" maxlength="10000"></textarea></label>
<label>Comment<textarea id="body" rows="5" maxlength="20000" required></textarea></label>
<label class="file">Add up to 3 images<input id="images" type="file" accept="image/png,image/jpeg,image/webp" multiple hidden></label><div id="previews"></div>
<button class="primary" type="submit">Post annotation</button><p id="post-status" class="status" aria-live="polite"></p>
</form></section>
<section id="tab-nearby" class="tab"><div class="card"><div class="title"><b>Nearby GPS context</b><span id="location-state" class="pill">location needed</span></div><p class="muted">Annotations appear here when your browser position is inside their radius. Bare coordinates use the default <?= (int)$config['default_gps_radius_meters'] ?> m gate.</p><div id="nearby-list" class="feed"></div></div></section>
<section id="tab-feed" class="tab"><div class="card"><div class="title"><b>All context</b><button id="refresh">Refresh</button></div><p id="feed-status" class="status" aria-live="polite" role="status"></p><div id="feed" class="feed"></div></div></section>
<section id="tab-schemas" class="tab"><div class="card"><div class="title"><b>Structured anchor schemas</b><span class="pill">JSON</span></div><p class="muted">Install object-style JSON Schemas to make new target types available alongside URL, GPS, Time and YouTube.</p><label class="file">Install JSON schema<input id="schema-file" type="file" accept=".json,application/json" hidden></label><p id="schema-status" class="status" aria-live="polite"></p><div id="schemas"></div></div></section>
<section id="tab-account" class="tab"><div class="card"><div class="title"><b>Account</b><span id="web-account-pill" class="pill">checking</span></div><p id="web-account-status" class="status" aria-live="polite"></p><div id="web-auth-out"><div class="two"><form id="web-register"><b>Register</b><p id="web-register-help" class="muted">The first account becomes administrator; later accounts need an invite.</p><label>Username<input id="web-reg-user" maxlength="32" required></label><label>Display name<input id="web-reg-display" maxlength="100"></label><label>Password<input id="web-reg-pass" type="password" minlength="10" maxlength="200" required></label><label id="web-reg-invite-label">Invitation code<input id="web-reg-invite" maxlength="80"></label><button type="submit">Register</button></form><form id="web-login"><b>Log in</b><label>Username<input id="web-login-user" maxlength="32" required></label><label>Password<input id="web-login-pass" type="password" maxlength="200" required></label><button type="submit">Log in</button></form></div></div><div id="web-auth-in" class="hidden"><p>Logged in as <strong id="web-account-name"></strong>.</p><button id="web-logout" type="button">Log out</button></div></div></section></main><script type="module" src="assets/app.js"></script></body></html>
